apiVersion: v1
kind: ServiceAccount
metadata:
  name: webui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  labels:
    app: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
        version: v1
    spec:
      serviceAccountName: webui
      containers:
        - image: pj3677/webui
          imagePullPolicy: Always
          name: web
          ports:
            - containerPort: 3000
          env:
            # Remove this for Gloo Gateway scenario as we're doing auth 
            # at Gloo Gateway in that case and not at this service
            - name: SHOULD_AUTHENTICATE
              value: "true"
            - name: BACKEND_SERVICE_URL
              value: 'http://backend-api'
            - name: SECOND_BACKEND_SERVICE_URL
              value: 'http://second-backend-api'
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: webui-auth0
                  key: AUTH0_CLIENT_ID
            - name: AUTH0_SECRET
              valueFrom:
                secretKeyRef:
                  name: webui-auth0
                  key: AUTH0_SECRET
            - name: RANDOM_SECRET
              valueFrom:
                secretKeyRef:
                  name: webui-auth0
                  key: RANDOM_SECRET
            - name: ISSUER_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: webui-config
                  key: ISSUER_BASE_URL
            - name: AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: webui-config
                  key: AUDIENCE
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: webui-config
                  key: BASE_URL
---
kind: Service
apiVersion: v1
metadata:
  name: webui
  labels:
    app: webui
spec:
  selector:
    app: webui
  ports:
    - port: 80
      name: http
      targetPort: 8080